config/routes.rb
Rails.application.routes.draw do
  root 'campaigns#index'
  resources :campaigns
  resources :cuepoints do
    resources :campaigns, only: [:index]
  end
  get 'results', to: 'results#index'
  get 'results/record'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
# キャンペーンクラス
class Campaign < ApplicationRecord
  # 有効なキャンペーン一覧を返す
  has_and_belongs_to_many :cuepoints
  
  #start以降じゃないとendを使えない

  validates :name, presence: true, uniqueness: true, length: { in: 5..20 }
  validates :movie_url, presence: true, length: { in: 5..100 }
  validates_datetime :start_at
  validates_datetime :end_at, on_or_after: :start_at  
  #  - 対象のCue Pointと紐付いている。
  #  - キャンペーンが開始していて、終了する前。
  #  - Resultのスタート数(count_start)がキャンペーンの制限(limit_start)以内。
  # @param [Cuepoint, #read] cuepoint キャンペーンの対象となっている Cue Point
  # @return [Array] 該当キャンペーンの配列
  def self.current_avaliable(cuepoint)
    ccc = cuepoint.campaigns.
      where("start_at <= '#{Time.now}' AND end_at >= '#{Time.now}'")
    return ccc.reject do |campaign|
      result = Result.where(campaign: campaign, cuepoint: cuepoint).first
      !result.blank? && result.count_start >= campaign.limit_start
    end
  end
end

app/models/cuepoint.rb
# キューポイントクラス
class Cuepoint < ApplicationRecord
  # TODO
  has_and_belongs_to_many :campaigns
  
  validates :name, presence: true, uniqueness: true, length: { in: 5..20 }
end

app/models/result.rb
# 結果クラス
class Result < ApplicationRecord
  # TODO
  after_initialize :zero_clear
  belongs_to :campaign
  belongs_to :cuepoint

  private
    # 初期化
    def zero_clear
      # TODO
      # 広告読み込み開始(count_start)の初期化 ||= 
      # 広告読み込み完了(count_complete)の初期化　||= 
      self.count_start ||= 0
      self.count_complete ||= 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
# キャンペーン用コントローラ
class CampaignsController < ApplicationController
  # 一覧表示
  def index
    unless params[:cuepoint_id]
      # TODO
      @campaigns = Campaign.all
    else
      # 下記はVAST URL呼び出しを想定
      # TODO
      @cuepoint = Cuepoint.find(params[:cuepoint_id])
      @campaigns = Campaign.current_avaliable(@cuepoint)
      response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
      response.headers['Access-Control-Allow-Methods'] = 'GET'
      headers['Access-Control-Request-Method'] = '*'
      headers['Access-Control-Allow-Credentials'] = 'true'
      headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type'
    end
  end

# 新規
  def new
    @campaign = Campaign.new
  end

  # 作成
  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      flash[:success] = '正常に追加されました'
      redirect_to campaigns_path
    else
      flash.now[:danger] = '正常に追加されませんでした'
      render :new
    end
  end

  # 編集
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # 更新
  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update(campaign_params)
      flash[:success] = '正常に更新されました'
      redirect_to campaigns_path
    else
      flash.now[:danger] = '正常に更新されませんでした'
      render :edit
    end
  end

  # 削除
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    flash[:success] = '正常に削除されました'
    redirect_to campaigns_url
  end

  private
    # キャンペーン用パラメータ
    def campaign_params
      params.require(:campaign).permit(:name, :start_at, :end_at, :limit_start, :movie_url, :cuepoint_ids=>[])
    end
end

app/controllers/cuepoints_controller.rb
# Cue Point コントローラ
class CuepointsController < ApplicationController
  # 一覧
  def index
    @cuepoints = Cuepoint.all
  end

  # 新規
  def new
    @cuepoint = Cuepoint.new
  end

  # 作成
  def create
    @cuepoint = Cuepoint.new(cuepoint_params)

    if @cuepoint.save
      flash[:success] = '正常に追加されました'
      redirect_to cuepoints_path
    else
      flash.now[:danger] = '正常に追加されませんでした'
      render :new
    end
  end

  # 編集
  def edit
    @cuepoint = Cuepoint.find(params[:id])
  end

  # 更新
  def update
    @cuepoint = Cuepoint.find(params[:id])

    if @cuepoint.update(cuepoint_params)
      flash[:success] = '正常に更新されました'
      redirect_to cuepoints_path
    else
      flash.now[:danger] = '正常に更新されませんでした'
      render :new
    end
  end

  # 削除
  def destroy
    @cuepoint = Cuepoint.find(params[:id])
    @cuepoint.destroy

    flash[:success] = '正常に削除されました'
    redirect_to cuepoints_url
  end

  private
    # キューポイント用パラメータ
    def cuepoint_params
      params.require(:cuepoint).permit(:name)
    end
end

app/controllers/results_controller.rb
# レポート関連コントローラ
class ResultsController < ApplicationController
  # 結果一覧表示
  def index
    @results = Result.all.order(:campaign_id, :cuepoint_id)
  end

  # 結果追加
  def record
    # TODO
    @result = Result.find_or_initialize_by(campaign_id: params[:campaign], cuepoint_id: params[:cuepoint])
    logger.debug @result.inspect
    if params[:event] == 'start'
      @result.count_start += 1
    elsif params[:event] == 'complete'
      @result.count_complete += 1
    end
    @result.save!
    send_data(Base64.decode64('R0lGODlhAQABAPAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=='),
      type: 'image/gif', disposition: 'inline')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def track_url(campaign, cuepoint, event)
    url = request.protocol + request.host_with_port + '/results/record?'
    url += { campaign: campaign, cuepoint: @cuepoint, event: event }.to_query
    url
  end

  def vast_url(cuepoint)
    request.protocol + request.host_with_port + cuepoint_campaigns_path(@cuepoint) + '.xml'
  end
end

app/views/campaigns/edit.html.erb
<h1>キャンペーン編集</h1>

<%= form_for(@campaign) do |f| %>
  <%= render "shared/error_messages", :object => @campaign %>

<div class="form-group">  
　<%= f.label :name, 'キャンペーン名' %>
　<%= f.text_field :name %>
</div>

<div class="form-group">
 <%= f.label :start_at, '開始日時' %>
 <%= f.text_field :start_at %>
</div>

<div class="form-group">
 <%= f.label :end_at, '終了日時' %>
 <%= f.text_field :end_at %>
</div>

<div class="form-group">
 <%= f.label :limit_start, 'ゴールimp' %>
 <%= f.text_field :limit_start %>
</div>

<div class="form-group">
 <%= f.label :movie_url, '動画URL' %>
 <%= f.text_field :movie_url %>
</div>

<div class="check_box" >
    <%= f.label :cuepoint, 'キューポイント' %><br>
    <%= f.collection_check_boxes(:cuepoint_ids, Cuepoint.all, :id, :name) do |b| %>
      <%= b.label { b.check_box + b.text } %>
    <% end %>
</div>

<%= f.submit '変更', class: 'btn btn-primary' %>
<%= link_to '削除', @campaign, method: :delete, data: { confirm: '削除してよろしいですか？一旦削除すると元には戻せません。' }, class: 'btn btn-danger' %>
<%= link_to '中止', campaigns_path, class: 'btn btn-warning' %>

<% end %>

app/views/campaigns/index.html.erb
<h1>キャンペーン一覧</h1>
<%= link_to '登録', new_campaign_path, class: 'btn btn-primary' %> 
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>名前</th>
        <th>開始日時</th>
        <th>終了日時</th>
        <th>ゴール</th>
        <th>作成日時</th>
        <th>更新日時</th>
      </tr>
    </thead>
    <tbody>
      
<% @campaigns.each do |campaign| %>

        <tr>
          <td><%= link_to campaign.id, edit_campaign_path(campaign) %></td>
          <td><%= campaign.name %></td>
          <td><%= campaign.start_at %></td>
          <td><%= campaign.end_at %></td>
          <td><%= campaign.limit_start %></td>
          <td><%= campaign.created_at %></td>
          <td><%= campaign.updated_at %></td>
        </tr>
      
<% end %>

   </tbody>
  </table>

app/views/campaigns/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="2.0">
  <% if @campaigns.length > 0 %>
  <Ad>
    <InLine>
      <Creatives>
        <% campaign = @campaigns.sample %>
        <Creative>
          <Linear>
            <Duration>00:00:15</Duration>
            <MediaFiles>
              <MediaFile delivery="progressive" type="video/mp4">
                <![CDATA[ <%= campaign.movie_url %> ]]>
              </MediaFile>
            </MediaFiles>
            <TrackingEvents>
              <Tracking event="start"><![CDATA[ <%= raw(track_url(campaign,@cuepoint,"start"))  %> ]]></Tracking>
              <Tracking event="complete"><![CDATA[ <%= raw(track_url(campaign,@cuepoint,"complete")) %> ]]></Tracking>
            </TrackingEvents>
          </Linear>
        </Creative>
      </Creatives>
    </InLine>
  </Ad>
  <% end %>
</VAST>

app/views/campaigns/new.html.erb
<h1>キャンペーン登録</h1>
<%= form_for(@campaign) do |f| %>
  <%= render "shared/error_messages", :object => @campaign %>

  
<%= f.label :name, 'キャンペーン名' %>
<%= f.text_field :name %><br>

<%= f.label :start_at, '開始日時' %>
<%= f.text_field :start_at %><br>

<%= f.label :start_at, '終了日時' %>
<%= f.text_field :end_at %><br>

<%= f.label :limit_start, 'ゴールimp' %>
<%= f.text_field :limit_start %><br>

<%= f.label :movie_url, '動画URL' %>
<%= f.text_field :movie_url %><br>

<div class="check_box" >
    <%= f.label :cuepoint, 'キューポイント' %><br>
    <%= f.collection_check_boxes(:cuepoint_ids, Cuepoint.all, :id, :name) do |b| %>
      <%= b.label { b.check_box + b.text } %>
    <% end %>
</div>
 
<%= f.submit '登録', class: 'btn btn-primary' %>
<%= link_to '中止', campaigns_path, class: 'btn btn-warning' %>

<% end %>

app/views/cuepoints/edit.html.erb
<h1>キューポイント編集</h1>

<%= form_for(@cuepoint) do |f| %>
  <%= render "shared/error_messages", :object => @cuepoint %>
  
<%= f.label :name, 'キューポイント名' %>
<%= f.text_field :name %><br>

<%= f.label 'VAST URL ：' %>
<%= link_to vast_url(@cuepoint), vast_url(@cuepoint) %><br>

  
<%= f.submit '変更', class: 'btn btn-primary' %>
<%= link_to '削除', @cuepoint, method: :delete, data: { confirm: '削除してよろしいですか？一旦削除すると元には戻せません。' }, class: 'btn btn-danger' %>
<%= link_to '中止', cuepoints_path, class: 'btn btn-warning' %>

<% end %>

app/views/cuepoints/index.html.erb
<h1>キューポイント一覧</h1>

<%= link_to '登録', new_cuepoint_path, class: 'btn btn-primary' %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>名前</th>
        <th>作成日</th>
        <th>更新日</th>
      </tr>
    </thead>
    <tbody>
      
<% @cuepoints.each do |cuepoint| %>

        <tr>
          <td><%= link_to cuepoint.id, edit_cuepoint_path(cuepoint) %></td>
          <td><%= cuepoint.name %></td>
          <td><%= cuepoint.created_at %></td>
          <td><%= cuepoint.updated_at %></td>
        </tr>
      
<% end %>

   </tbody>
  </table>

app/views/cuepoints/new.html.erb
<h1>キューポイント登録</h1>
<%= form_for(@cuepoint) do |f| %>
  <%= render "shared/error_messages", :object => @cuepoint %>

  
<%= f.label :name, 'キューポイント名' %>

  
<%= f.text_field :name %>


  
<%= f.submit '登録', class: 'btn btn-primary' %>
<%= link_to '中止', cuepoints_path, class: 'btn btn-warning' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "DacVast" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>


  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarTop">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          DAC VAST Server
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbarTop">
        <ul class="nav navbar-nav">
          <li class="nav-item <%= controller.controller_name == 'campaigns' ? 'active' : ''%>"><%= link_to "Campaigns", "/campaigns"  %></li>
          <li class="nav-item <%= controller.controller_name == 'cuepoints' ? 'active' : ''%>"><%= link_to "Cuepoints", "/cuepoints"  %></li>
          <li class="nav-item <%= controller.controller_name == 'results' ? 'active' : ''%>"><%= link_to "Results", "/results"  %></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>

        <%= yield %>
      </div>
    </div><!--/row-->

  </div> <!-- /container -->

  <footer class="footer">
    <div class="container">
      <p class="text-muted">&copy; DAC 新卒研修</p>
    </div>
  </footer>

</body>
</html>

app/views/results/index.html.erb
<h1>Results</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>キャンペーン</th>
        <th>id</th>
        <th>キューポイント</th>
        <th>開始数</th>
        <th>完了数</th>
      </tr>
    </thead>
    <tbody>
      
<% @results.each do |result| %>

        <tr>
          <td><%= result.campaign.id %></td>
          <td><%= result.campaign.name %></td>
          <td><%= result.cuepoint.id %></td>
          <td><%= result.cuepoint.name %></td>
          <td><%= result.count_start %></td>
          <td><%= result.count_complete %></td>
        </tr>
      
<% end %>

   </tbody>
  </table>

app/views/results/record.html.erb
  <h1>Results#add</h1>
<p>Find me in app/views/results/add.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>